### ISSUE TITLE
This list has very few repos in it

### ISSUE THREAD

**Issue by lanmower** [openhive-network/awesome-hive#14]
Awesome lists are used by devs to find repos, this is more like a marketing page, make a github sites page out of it and call it something else, then leave the repos in here and call that awesome-hive.

There is zero need to put closed source projects in an awesome- list, these lists are used by devs to google up repos that they can use for example code, you're diluting those search results with marketing content that all the users will have to ignore, since none of them are looking for a site to post their grandmothers selfie on, they're all looking for code repos.

**Comment by Gandalf-the-Grey** [comment]
No.
Quote from main repo:

> An awesome list is a list of awesome things curated by the community. There are awesome lists about everything from CLI applications to fantasy books.

**Comment by lanmower** [comment]
using the awesome paradigm to advertise closed source websites is shameless
plugging

**Comment by Gandalf-the-Grey** [comment]
Apparently you have no idea what awesome lists really are. But that's OK. Please read the guidelines and requirements and if you think you can create better one, you are welcome to do so. Good luck! :-)

**Comment by lanmower** [comment]
![image](https://user-images.githubusercontent.com/657315/149987987-caf1b511-c18f-44a7-af66-5b73cbed94cb.png)
You dont, that was the point of this issue.

**Comment by lanmower** [comment]
![image](https://user-images.githubusercontent.com/657315/149988242-6a252590-2725-4694-bd4d-6969eae06f2c.png)
